# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af72d865f6b4e36cc85e1782b28f5bab487bcd68912ce1252ac7d1414ef9e2dddc64ab24caffdadb0b84985ac98e18220ef08355fd2619cb4426897c43789f58

test:
  secret_key_base: 55a2ee417d04c4ae291cc3a53d89432d1e4e1233c97ad69fa6dfe91134b8bdd5ca8d5b4542beef8be9dcdfaaf4810875073e47285ada021ff317e42cbadb6995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
